sudo: required
services:
  - docker

before_install:
  - docker build -t hedgehocrow/docker-react -f Dockerfile.dev .

script:
  - docker run hedgehocrow/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: $S3_BUCKET_NAME
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
